# Server parameters
ip_addr: 0.0.0.0
port: 8080
# Concurrency parameters
maximum_connections: 10240
maximum_events: 10240
event_polls: 5
read_workers: 10
process_workers: 10
write_workers: 10
# Logger parameters
info: false
error: false
warn: false
debug: false